In [1]:
#importamos las librerías necesarias para la exploración inicial

from pathlib import Path
import pandas as pd
import numpy as np
import json

In [2]:
# Preparamos rutas, localizamos archivos y mostramos sus características

#dataset original
DATA_DIR = Path("../Data/RAW")

#dataset limpio
OUTPUT_DIR = Path("../Data/Clean")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

csv_files = sorted(DATA_DIR.glob("*.csv"))

print(f"Archivos CSV encontrados: {len(csv_files)}\n")

for file in csv_files:
    print(f"{file.name:40} {file.stat().st_size / (1024**2):8.2f} MB")

Archivos CSV encontrados: 11

hourly_weather.csv                           2.78 MB
Ing_in_item.csv                              0.00 MB
Ingredient.csv                               0.01 MB
Item_on_receipt.csv                         56.48 MB
Menu_item.csv                                0.03 MB
Payment.csv                                 22.50 MB
Receipt.csv                                 68.09 MB
SA1_AppWichStoreAttributes.csv               0.00 MB
SA1_county_crime.csv                         0.00 MB
SA1_county_demographic.csv                   0.00 MB
SA1_county_employment.csv                    0.00 MB

In [3]:
#cargamos archivos CSV, comprobamos su lectura
#y dfinimos el tratamiento inicial de valores nulos

datasets = {}

for file in csv_files:
    try:
        df = pd.read_csv(
            file,
            encoding = "utf-8-sig",
            low_memory=False,
            keep_default_na=False,
            na_values=[""]
        )

        datasets[file.stem] = df

        print(f"{file.name}: "
             f"{df.shape[0]}"
             )
    except Exception as e:
        print (f"Error leyendo {file.name}: {e}")

hourly_weather.csv: 42909
Ing_in_item.csv: 78
Ingredient.csv: 279
Item_on_receipt.csv: 1048575
Menu_item.csv: 560
Payment.csv: 580453
Receipt.csv: 575507
SA1_AppWichStoreAttributes.csv: 10
SA1_county_crime.csv: 6
SA1_county_demographic.csv: 6
SA1_county_employment.csv: 6

In [4]:
#visualizamos el contenido de cada tabla
#y guardamos la información en un dataframe de pandas

inventory = []

for name, df in datasets.items():
    inventory.append({
        "tabla":name,
        "filas":len(df),
        "columnas":len(df.columns),
        "columnas_lista":", ".join(map(str,df.columns))
    })

inventory_df = pd.DataFrame(inventory)

#mostramos la información utilizando la función display
display(
    inventory_df.sort_values("tabla").reset_index(drop=True)
)

,tabla,filas,columnas,columnas_lista
0,Ing_in_item,78,5,"Ingredient_ID, Inv_Num, Quantity, Unit, Unit_Amt"
1,Ingredient,279,2,"Ingredient_ID, Description"
2,Item_on_receipt,1048575,7,"Receipt_ID, Inv_Num, Price, Food_Cost, Count, ..."
3,Menu_item,560,7,"Inv_Num, Item_Description, Size, Cat_ID, Cat_D..."
4,Payment,580453,4,"Receipt_ID, Payment_ID, Pay_Type, Tender_Amt"
5,Receipt,575507,17,"Receipt_ID, Store_Num, Date, Start_Time, End_T..."
6,SA1_AppWichStoreAttributes,10,14,"Store_Name, Store_Num, Store_City, Store_Count..."
7,SA1_county_crime,6,12,"County_Name, County_Crime_Pop, County_Total_Cr..."
8,SA1_county_demographic,6,14,"County_Name, County_Total_Census_Pop, County_N..."
9,SA1_county_employment,6,5,"County_Name, County_Labor_Force, County_Employ..."
10,hourly_weather,42909,11,"Weather_Station, Date, Hour, Air_Temp, Dew_Poi..."

In [6]:
#Extraemos una muestra de los valores de las tablas

for name, df in datasets.items():
    print("="*20)
    print(f"Tabla: {name}")
    display(df.head(5))
    display(df.dtypes.rename("tipo actual").to_frame())
    print("*"*20)

====================
Tabla: hourly_weather

,Weather_Station,Date,Hour,Air_Temp,Dew_Point,Pressure,Wind_Dir,Wind_Spd,Sky_Cond,Precip_1hr,Precip_6hr
0,River City Airport,4/1/12,0,44.96,35.96,29.529884,160.0,4.6977,0.0,0.0,NaN
1,River City Airport,4/1/12,1,46.94,32.00,29.535790,190.0,10.2902,0.0,0.0,NaN
2,River City Airport,4/1/12,2,48.92,33.08,29.547602,180.0,9.1717,8.0,0.0,NaN
3,River City Airport,4/1/12,3,50.00,32.00,29.574179,180.0,13.8694,8.0,0.0,NaN
4,River City Airport,4/1/12,4,48.92,32.00,29.627333,220.0,16.1064,8.0,-1.0,NaN

                tipo actual
Weather_Station      object
Date                 object
Hour                  int64
Air_Temp            float64
Dew_Point           float64
Pressure            float64
Wind_Dir            float64
Wind_Spd            float64
Sky_Cond            float64
Precip_1hr          float64
Precip_6hr          float64

********************
====================
Tabla: Ing_in_item

   Ingredient_ID  Inv_Num  Quantity  Unit  Unit_Amt
0           1501    11291         1  EACH         1
1           1621    11291         1  EACH         1
2           1641    11291         1  EACH         1
3           1661    11291         1  EACH         1
4          13751    11291         1  EACH         1

              tipo actual
Ingredient_ID       int64
Inv_Num             int64
Quantity            int64
Unit               object
Unit_Amt            int64

********************
====================
Tabla: Ingredient

   Ingredient_ID                   Description
0           1501                   REGULAR BMT
1           1621            REGULAR ROAST BEEF
2           1641  REGULAR TURKEY/HAM/ROASTBEEF
3           1661   REGULAR SAVORY TURKEY & HAM
4          13751         REGULAR SPICY ITALIAN

              tipo actual
Ingredient_ID       int64
Description        object

********************
====================
Tabla: Item_on_receipt

,Receipt_ID,Inv_Num,Price,Food_Cost,Count,Sales_Total,Cost_Total
0,16_04/01/2012_17:32_10052_0,11,3.75,1.0124,1,3.75,1.0124
1,16_04/01/2012_17:32_10052_0,1511,5.00,1.9839,1,5.00,1.9839
2,16_04/01/2012_17:32_10052_0,11520,1.75,0.6230,1,1.75,0.6230
3,16_04/01/2012_17:32_10052_0,35048,5.50,1.3551,1,5.50,1.3551
4,16_04/01/2012_11:33_10012_0,111,3.75,1.0264,1,3.75,1.0264

            tipo actual
Receipt_ID       object
Inv_Num           int64
Price           float64
Food_Cost       float64
Count             int64
Sales_Total     float64
Cost_Total      float64

********************
====================
Tabla: Menu_item

,Inv_Num,Item_Description,Size,Cat_ID,Cat_Description,Sub_Cat_ID,Sub_Cat_Description
0,35069,2 BREAKFAST 4 $3.00,NaN,9,BREAKFAST,3,BREAKFAST DELI
1,9515,$1 OFF PREMIUM SUB,NaN,8,COUPONS,1,FOOTLONG
2,4009,$1.00 OFF REGULAR SUB,NaN,8,COUPONS,1,FOOTLONG
3,4011,$1.00 OFF REGULAR & 21OZ,NaN,8,COUPONS,1,FOOTLONG
4,4038,$1.00 OFF SALAD,NaN,8,COUPONS,8,SALAD

                    tipo actual
Inv_Num                   int64
Item_Description         object
Size                     object
Cat_ID                    int64
Cat_Description          object
Sub_Cat_ID                int64
Sub_Cat_Description      object

********************
====================
Tabla: Payment

                    Receipt_ID  Payment_ID Pay_Type  Tender_Amt
0      16_04/01/2012_10:33_1_0           1     VISA        7.55
1  16_04/01/2012_10:53_10004_0           1     CASH        5.40
2  16_04/01/2012_11:01_10006_0           1     VISA       14.84
3  16_04/01/2012_11:23_10008_0           1     CASH       20.02
4  16_04/01/2012_11:28_10010_0           1     CASH       16.29

           tipo actual
Receipt_ID      object
Payment_ID       int64
Pay_Type        object
Tender_Amt     float64

********************
====================
Tabla: Receipt

,Receipt_ID,Store_Num,Date,Start_Time,End_Time,Check_Num,Return,Drive_Thru,Server_Name,Server_Title,Cashier_Name,Cashier_Title,Sub_Total,Tax,Discount_Type,Discount_Amt,Total
0,16_04/02/2012_07:31_10001_0,16,4/2/12,7:31,7:31,10001,0,0,ALLYSON SAMANIEGO,NaN,ALLYSON SAMANIEGO,NaN,3.75,0.30,NaN,0.0,4.05
1,16_04/02/2012_07:47_10003_0,16,4/2/12,7:47,7:47,10003,0,0,ALLYSON SAMANIEGO,NaN,ALLYSON SAMANIEGO,NaN,4.00,0.32,NaN,0.0,4.32
2,16_04/02/2012_08:01_10004_0,16,4/2/12,8:01,8:01,10004,0,0,ALLYSON SAMANIEGO,NaN,ALLYSON SAMANIEGO,NaN,2.50,0.20,NaN,0.0,2.70
3,16_04/02/2012_08:18_10006_0,16,4/2/12,8:18,8:18,10006,0,0,ALLYSON SAMANIEGO,NaN,ALLYSON SAMANIEGO,NaN,4.00,0.32,NaN,0.0,4.32
4,16_04/02/2012_08:31_10007_0,16,4/2/12,8:29,8:31,10007,0,0,ALLYSON SAMANIEGO,NaN,ALLYSON SAMANIEGO,NaN,0.69,0.05,NaN,0.0,0.74

              tipo actual
Receipt_ID         object
Store_Num           int64
Date               object
Start_Time         object
End_Time           object
Check_Num           int64
Return              int64
Drive_Thru          int64
Server_Name        object
Server_Title       object
Cashier_Name       object
Cashier_Title      object
Sub_Total         float64
Tax               float64
Discount_Type      object
Discount_Amt      float64
Total             float64

********************
====================
Tabla: SA1_AppWichStoreAttributes

,Store_Name,Store_Num,Store_City,Store_County,Store_State,Store_Weather_Station,Store_Location,Store_Drive_Through,Store_Near_School,Store_Competition_Fastfood,Store_Competition_Otherfood,Store_Traveller_Clients,Store_Minority_Clients,Annual_Rent_Estimate
0,Power City FreeStand,2,Power City,Power County,North State,Rail City Airport,Free Standing,Yes,Yes,10,25,No,NaN,63000
1,West Power StripMall,5,West Power City,Power County,North State,Rail City Airport,Strip Mall,No,No,1,9,No,NaN,48600
2,Power City StripMall,7,Power City,Power County,North State,Rail City Airport,Strip Mall,No,No,5,6,No,NaN,54000
3,Littletown StripMall,9,Littletown,Appleton County,North State,Appleton Airport,Strip Mall,No,No,7,18,Yes,"Hispanic, Native American",36000
4,River City StripMall,11,River City,River County,North State,River City Airport,Strip Mall,No,Yes,8,30,No,NaN,45000

                            tipo actual
Store_Name                       object
Store_Num                         int64
Store_City                       object
Store_County                     object
Store_State                      object
Store_Weather_Station            object
Store_Location                   object
Store_Drive_Through              object
Store_Near_School                object
Store_Competition_Fastfood        int64
Store_Competition_Otherfood       int64
Store_Traveller_Clients          object
Store_Minority_Clients           object
Annual_Rent_Estimate             object

********************
====================
Tabla: SA1_county_crime

,County_Name,County_Crime_Pop,County_Total_Crimes,County_Total_Crime_Rate,County_Violent_Crimes,County_Violent_Rate,County_Property_Crimes,County_Property_Rate,County_Society_Crimes,County_Society_Rate,County_Other_Crimes,County_Other_Rate
0,Appleton County,159808.0,17393.0,108.8,2932.0,18.347016,12171.0,76.2,1572.0,9.8,718.0,4.492891
1,Farm County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Lake County,85945.0,7418.0,86.3,1294.0,15.056141,5288.0,61.5,599.0,7.0,237.0,2.757578
3,Power County,174226.0,11993.0,68.8,2250.0,12.914261,7507.0,43.1,1744.0,10.0,492.0,2.823918
4,Rail County,82500.0,5219.0,63.3,1055.0,12.787879,3245.0,39.3,666.0,8.1,253.0,3.066667

                        tipo actual
County_Name                  object
County_Crime_Pop            float64
County_Total_Crimes         float64
County_Total_Crime_Rate     float64
County_Violent_Crimes       float64
County_Violent_Rate         float64
County_Property_Crimes      float64
County_Property_Rate        float64
County_Society_Crimes       float64
County_Society_Rate         float64
County_Other_Crimes         float64
County_Other_Rate           float64

********************
====================
Tabla: SA1_county_demographic

,County_Name,County_Total_Census_Pop,County_Non-Hispanic_White,County_Non-Hispanic_Black,County_Non-Hispanic_Native_American,County_Non-Hispanic_Asian,County_Non-Hispanic_Pacific_Islander,County_Non-Hispanic_Two_or_more,County_Hispanic_White,County_Hispanic_Black,County_Hispanic_Native_American,County_Hispanic_Asian,County_Hispanic_Pacific_Islander,County_Hispanic_Two_or_more
0,Appleton County,246977,114474,1918,9195,2629,183,4200,103919,1590,5002,870,312,2685
1,Farm County,76820,52523,596,2443,708,105,1439,17409,193,838,132,36,398
2,Lake County,91723,51806,788,774,851,73,1509,33452,804,941,154,51,520
3,Power County,182398,134533,2265,1351,5089,223,3963,32294,485,776,278,112,1029
4,Rail County,85845,37009,1702,421,1593,123,1267,41344,549,721,232,204,680

                                     tipo actual
County_Name                               object
County_Total_Census_Pop                    int64
County_Non-Hispanic_White                  int64
County_Non-Hispanic_Black                  int64
County_Non-Hispanic_Native_American        int64
County_Non-Hispanic_Asian                  int64
County_Non-Hispanic_Pacific_Islander       int64
County_Non-Hispanic_Two_or_more            int64
County_Hispanic_White                      int64
County_Hispanic_Black                      int64
County_Hispanic_Native_American            int64
County_Hispanic_Asian                      int64
County_Hispanic_Pacific_Islander           int64
County_Hispanic_Two_or_more                int64

********************
====================
Tabla: SA1_county_employment

,County_Name,County_Labor_Force,County_Employed,County_Unemployed,County_Unemployment_Rate
0,Appleton County,"121,082","108,267","12,815",10.6
1,Farm County,"36,674","33,354","3,320",9.1
2,Lake County,"43,914","39,740","4,174",9.5
3,Power County,"92,041","83,467","8,574",9.3
4,Rail County,"39,167","35,366","3,801",9.7

                         tipo actual
County_Name                   object
County_Labor_Force            object
County_Employed               object
County_Unemployed             object
County_Unemployment_Rate     float64

********************